/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_login_window (void);
GtkWidget* create_work_pane (void);
GtkWidget* create_prefs_window (void);
GtkWidget* create_fontselectiondialog (void);
GtkWidget* create_export_fileselector (void);
GtkWidget* create_help_window (void);
GtkWidget* create_save_query_fileselector (void);
GtkWidget* create_directory_fileselector (void);
GtkWidget* create_bookmark_organiser (void);
GtkWidget* create_add_bm_dialog (void);
GtkWidget* create_edit_bm_dialog (void);
GtkWidget* create_create_bmdir_dialog (void);
GtkWidget* create_print_dialog (void);
